#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE,
	PLAYER_RUN,
	PLAYER_COMBAT,
	PLAYER_SHOOT,
	NUM_OF_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/